frontend:
 image: sunnysinghgithub/smart-reader-frontend
 command: bash -c "cd appsource && npm install && npm start"
 volumes:
  - "./frontend/appsource:/appsource"
  - "./frontend/certs:/certs"
 ports:
  - "80:80"
  - "443:443"
 environment:
  - NODE_PATH=/usr/lib/node_modules
 links:
  - backend
  - mongodb
 restart: always
backend:
 image: sunnysinghgithub/smart-reader-backend
 volumes:
  - "./backend/appsource:/appsource"
 command: bash -c "cd appsource && python hellorpc.py"
 ports:
  - "5000:5000"
 restart: always
mongodb:
 image: mongo
 command: mongod --smallfiles
